use serde::{Deserialize, Serialize};
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SerializableKeycode {
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    Escape,
    Space,
    LControl,
    RControl,
    LShift,
    RShift,
    LAlt,
    RAlt,
    Command,
    RCommand,
    LOption,
    ROption,
    LMeta,
    RMeta,
    Enter,
    Up,
    Down,
    Left,
    Right,
    Backspace,
    CapsLock,
    Tab,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadSubtract,
    NumpadAdd,
    NumpadDivide,
    NumpadMultiply,
    NumpadEquals,
    NumpadEnter,
    NumpadDecimal,
    Grave,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
    Unknown(String),
}

#[cfg(target_arch = "wasm32")]
impl From<egui::Key> for crate::shortcut::keycodes::SerializableKeycode {
    fn from(key: egui::Key) -> Self {
        match key {
            egui::Key::A => SerializableKeycode::A,
            egui::Key::B => SerializableKeycode::B,
            egui::Key::C => SerializableKeycode::C,
            egui::Key::D => SerializableKeycode::D,
            egui::Key::E => SerializableKeycode::E,
            egui::Key::F => SerializableKeycode::F,
            egui::Key::G => SerializableKeycode::G,
            egui::Key::H => SerializableKeycode::H,
            egui::Key::I => SerializableKeycode::I,
            egui::Key::J => SerializableKeycode::J,
            egui::Key::K => SerializableKeycode::K,
            egui::Key::L => SerializableKeycode::L,
            egui::Key::M => SerializableKeycode::M,
            egui::Key::N => SerializableKeycode::N,
            egui::Key::O => SerializableKeycode::O,
            egui::Key::P => SerializableKeycode::P,
            egui::Key::Q => SerializableKeycode::Q,
            egui::Key::R => SerializableKeycode::R,
            egui::Key::S => SerializableKeycode::S,
            egui::Key::T => SerializableKeycode::T,
            egui::Key::U => SerializableKeycode::U,
            egui::Key::V => SerializableKeycode::V,
            egui::Key::W => SerializableKeycode::W,
            egui::Key::X => SerializableKeycode::X,
            egui::Key::Y => SerializableKeycode::Y,
            egui::Key::Z => SerializableKeycode::Z,
            egui::Key::Num0 => SerializableKeycode::Key0,
            egui::Key::Num1 => SerializableKeycode::Key1,
            egui::Key::Num2 => SerializableKeycode::Key2,
            egui::Key::Num3 => SerializableKeycode::Key3,
            egui::Key::Num4 => SerializableKeycode::Key4,
            egui::Key::Num5 => SerializableKeycode::Key5,
            egui::Key::Num6 => SerializableKeycode::Key6,
            egui::Key::Num7 => SerializableKeycode::Key7,
            egui::Key::Num8 => SerializableKeycode::Key8,
            egui::Key::Num9 => SerializableKeycode::Key9,
            egui::Key::Enter => SerializableKeycode::Enter,
            egui::Key::Escape => SerializableKeycode::Escape,
            egui::Key::Tab => SerializableKeycode::Tab,
            egui::Key::Backspace => SerializableKeycode::Backspace,
            egui::Key::Insert => SerializableKeycode::Insert,
            egui::Key::Delete => SerializableKeycode::Delete,
            egui::Key::Home => SerializableKeycode::Home,
            egui::Key::End => SerializableKeycode::End,
            egui::Key::PageUp => SerializableKeycode::PageUp,
            egui::Key::PageDown => SerializableKeycode::PageDown,
            egui::Key::ArrowUp => SerializableKeycode::Up,
            egui::Key::ArrowDown => SerializableKeycode::Down,
            egui::Key::ArrowLeft => SerializableKeycode::Left,
            egui::Key::ArrowRight => SerializableKeycode::Right,
            egui::Key::Space => SerializableKeycode::Space,
            egui::Key::F1 => SerializableKeycode::F1,
            egui::Key::F2 => SerializableKeycode::F2,
            egui::Key::F3 => SerializableKeycode::F3,
            egui::Key::F4 => SerializableKeycode::F4,
            egui::Key::F5 => SerializableKeycode::F5,
            egui::Key::F6 => SerializableKeycode::F6,
            egui::Key::F7 => SerializableKeycode::F7,
            egui::Key::F8 => SerializableKeycode::F8,
            egui::Key::F9 => SerializableKeycode::F9,
            egui::Key::F10 => SerializableKeycode::F10,
            egui::Key::F11 => SerializableKeycode::F11,
            egui::Key::F12 => SerializableKeycode::F12,
            _ => SerializableKeycode::Unknown(format!("{:?}", key)),
        }
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl From<device_query::Keycode> for crate::shortcut::keycodes::SerializableKeycode {
    fn from(key: device_query::Keycode) -> Self {
        match key {
            device_query::Keycode::Key0 => SerializableKeycode::Key0,
            device_query::Keycode::Key1 => SerializableKeycode::Key1,
            device_query::Keycode::Key2 => SerializableKeycode::Key2,
            device_query::Keycode::Key3 => SerializableKeycode::Key3,
            device_query::Keycode::Key4 => SerializableKeycode::Key4,
            device_query::Keycode::Key5 => SerializableKeycode::Key5,
            device_query::Keycode::Key6 => SerializableKeycode::Key6,
            device_query::Keycode::Key7 => SerializableKeycode::Key7,
            device_query::Keycode::Key8 => SerializableKeycode::Key8,
            device_query::Keycode::Key9 => SerializableKeycode::Key9,

            device_query::Keycode::A => SerializableKeycode::A,
            device_query::Keycode::B => SerializableKeycode::B,
            device_query::Keycode::C => SerializableKeycode::C,
            device_query::Keycode::D => SerializableKeycode::D,
            device_query::Keycode::E => SerializableKeycode::E,
            device_query::Keycode::F => SerializableKeycode::F,
            device_query::Keycode::G => SerializableKeycode::G,
            device_query::Keycode::H => SerializableKeycode::H,
            device_query::Keycode::I => SerializableKeycode::I,
            device_query::Keycode::J => SerializableKeycode::J,
            device_query::Keycode::K => SerializableKeycode::K,
            device_query::Keycode::L => SerializableKeycode::L,
            device_query::Keycode::M => SerializableKeycode::M,
            device_query::Keycode::N => SerializableKeycode::N,
            device_query::Keycode::O => SerializableKeycode::O,
            device_query::Keycode::P => SerializableKeycode::P,
            device_query::Keycode::Q => SerializableKeycode::Q,
            device_query::Keycode::R => SerializableKeycode::R,
            device_query::Keycode::S => SerializableKeycode::S,
            device_query::Keycode::T => SerializableKeycode::T,
            device_query::Keycode::U => SerializableKeycode::U,
            device_query::Keycode::V => SerializableKeycode::V,
            device_query::Keycode::W => SerializableKeycode::W,
            device_query::Keycode::X => SerializableKeycode::X,
            device_query::Keycode::Y => SerializableKeycode::Y,
            device_query::Keycode::Z => SerializableKeycode::Z,

            device_query::Keycode::F1 => SerializableKeycode::F1,
            device_query::Keycode::F2 => SerializableKeycode::F2,
            device_query::Keycode::F3 => SerializableKeycode::F3,
            device_query::Keycode::F4 => SerializableKeycode::F4,
            device_query::Keycode::F5 => SerializableKeycode::F5,
            device_query::Keycode::F6 => SerializableKeycode::F6,
            device_query::Keycode::F7 => SerializableKeycode::F7,
            device_query::Keycode::F8 => SerializableKeycode::F8,
            device_query::Keycode::F9 => SerializableKeycode::F9,
            device_query::Keycode::F10 => SerializableKeycode::F10,
            device_query::Keycode::F11 => SerializableKeycode::F11,
            device_query::Keycode::F12 => SerializableKeycode::F12,
            device_query::Keycode::F13 => SerializableKeycode::F13,
            device_query::Keycode::F14 => SerializableKeycode::F14,
            device_query::Keycode::F15 => SerializableKeycode::F15,
            device_query::Keycode::F16 => SerializableKeycode::F16,
            device_query::Keycode::F17 => SerializableKeycode::F17,
            device_query::Keycode::F18 => SerializableKeycode::F18,
            device_query::Keycode::F19 => SerializableKeycode::F19,
            device_query::Keycode::F20 => SerializableKeycode::F20,

            device_query::Keycode::Escape => SerializableKeycode::Escape,
            device_query::Keycode::Space => SerializableKeycode::Space,
            device_query::Keycode::LControl => SerializableKeycode::LControl,
            device_query::Keycode::RControl => SerializableKeycode::RControl,
            device_query::Keycode::LShift => SerializableKeycode::LShift,
            device_query::Keycode::RShift => SerializableKeycode::RShift,
            device_query::Keycode::LAlt => SerializableKeycode::LAlt,
            device_query::Keycode::RAlt => SerializableKeycode::RAlt,
            device_query::Keycode::LMeta => SerializableKeycode::Command,

            device_query::Keycode::Enter => SerializableKeycode::Enter,
            device_query::Keycode::Up => SerializableKeycode::Up,
            device_query::Keycode::Down => SerializableKeycode::Down,
            device_query::Keycode::Left => SerializableKeycode::Left,
            device_query::Keycode::Right => SerializableKeycode::Right,
            device_query::Keycode::Backspace => SerializableKeycode::Backspace,
            device_query::Keycode::CapsLock => SerializableKeycode::CapsLock,
            device_query::Keycode::Tab => SerializableKeycode::Tab,
            device_query::Keycode::Home => SerializableKeycode::Home,
            device_query::Keycode::End => SerializableKeycode::End,
            device_query::Keycode::PageUp => SerializableKeycode::PageUp,
            device_query::Keycode::PageDown => SerializableKeycode::PageDown,
            device_query::Keycode::Insert => SerializableKeycode::Insert,
            device_query::Keycode::Delete => SerializableKeycode::Delete,

            device_query::Keycode::Numpad0 => SerializableKeycode::Numpad0,
            device_query::Keycode::Numpad1 => SerializableKeycode::Numpad1,
            device_query::Keycode::Numpad2 => SerializableKeycode::Numpad2,
            device_query::Keycode::Numpad3 => SerializableKeycode::Numpad3,
            device_query::Keycode::Numpad4 => SerializableKeycode::Numpad4,
            device_query::Keycode::Numpad5 => SerializableKeycode::Numpad5,
            device_query::Keycode::Numpad6 => SerializableKeycode::Numpad6,
            device_query::Keycode::Numpad7 => SerializableKeycode::Numpad7,
            device_query::Keycode::Numpad8 => SerializableKeycode::Numpad8,
            device_query::Keycode::Numpad9 => SerializableKeycode::Numpad9,
            device_query::Keycode::NumpadSubtract => SerializableKeycode::NumpadSubtract,
            device_query::Keycode::NumpadAdd => SerializableKeycode::NumpadAdd,
            device_query::Keycode::NumpadDivide => SerializableKeycode::NumpadDivide,
            device_query::Keycode::NumpadMultiply => SerializableKeycode::NumpadMultiply,
            device_query::Keycode::NumpadDecimal => SerializableKeycode::NumpadDecimal,
            device_query::Keycode::NumpadEnter => SerializableKeycode::NumpadEnter,

            device_query::Keycode::NumpadEquals => SerializableKeycode::Equal,
            device_query::Keycode::Grave => SerializableKeycode::Grave,
            device_query::Keycode::Minus => SerializableKeycode::Minus,
            device_query::Keycode::LeftBracket => SerializableKeycode::LeftBracket,
            device_query::Keycode::RightBracket => SerializableKeycode::RightBracket,
            device_query::Keycode::BackSlash => SerializableKeycode::BackSlash,
            device_query::Keycode::Semicolon => SerializableKeycode::Semicolon,
            device_query::Keycode::Apostrophe => SerializableKeycode::Apostrophe,
            device_query::Keycode::Comma => SerializableKeycode::Comma,
            device_query::Keycode::Dot => SerializableKeycode::Dot,
            device_query::Keycode::Slash => SerializableKeycode::Slash,

            other => SerializableKeycode::Unknown(format!("{:?}", other)),
        }
    }
}

impl fmt::Display for SerializableKeycode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SerializableKeycode::Unknown(s) => write!(f, "Unknown({})", s),
            _ => write!(f, "{:?}", self),
        }
    }
}